// <auto-generated />
namespace ViahealthHD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class changedpropname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedpropname));
        
        string IMigrationMetadata.Id
        {
            get { return "201808031402561_changedpropname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
